# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipfield',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
